name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Install Node
        uses: actions/setup-node@master
      - name: Build Site
        run: npm run release
      - name: Run a multi-line script
        run: echo "test the checkout action" && ls public